name: Auto Attendance

on:
  schedule:
    - cron: "0 9,12,13,17 * * 1-5"  # Runs at 09:00, 12:30, 13:30, and 17:00 on Monday to Friday

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install selenium

      - name: Run Python script
        run: python auto_attendance.py
        env:
          MOODLE_USERNAME: ${{ secrets.MOODLE_USERNAME }}
          MOODLE_PASSWORD: ${{ secrets.MOODLE_PASSWORD }}
